version: '2.4'
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark_net
    volumes:
      - hdfs-volume:/hdfs-tmp/:rw
      - master_volume_tmp:/tmp:rw
  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    networks:
      - spark_net
    volumes:
      - hdfs-volume:/hdfs-tmp/:rw
      - worker1_volume_tmp:/tmp:rw
  spark-worker-2:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8082:8081
    networks:
      - spark_net
    volumes:
      - hdfs-volume:/hdfs-tmp/:rw
      - worker2_volume_tmp:/tmp:rw
  spark-worker-3:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8083:8081
    networks:
      - spark_net
    volumes:
      - hdfs-volume:/hdfs-tmp/:rw
      - worker3_volume_tmp:/tmp:rw
networks:
  spark_net:
volumes:
  hdfs-volume:
  master_volume_tmp:
  worker1_volume_tmp:
  worker2_volume_tmp:
  worker3_volume_tmp:
