version: '2.4'
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=spark-search-test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
    networks:
      - hadoop_net
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    networks:
      - hadoop_net
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.8-hive-java8
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_net
  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.8-hive-java8
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_net
  spark-worker-2:
    image: bde2020/spark-worker:2.4.5-hadoop2.8-hive-java8
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8082:8081
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_net
  spark-worker-3:
    image: bde2020/spark-worker:2.4.5-hadoop2.8-hive-java8
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8083:8081
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_net
networks:
  hadoop_net:
    enable_ipv6: false