version: '2.4'
services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=spark-search-test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
    networks:
      - hadoop_net

  spark-hadoop-1:
    container_name: spark-hadoop-1
    build:
      context: .
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    networks:
      - hadoop_net

  spark-hadoop-2:
    build:
      context: .
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50076:50075
    networks:
      - hadoop_net

  spark-hadoop-3:
    build:
      context: .
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50077:50075
    networks:
      - hadoop_net
networks:
  hadoop_net: