version: '2.4'
services:

  namenode:
    build:
      context: .
      target: spark-namenode-yarn
    container_name: namenode
    environment:
      - CLUSTER_NAME=spark-search-test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
    networks:
      - hadoop_net

  spark-hadoop-1:
    build:
      context: .
      target: spark-worker-yarn
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    networks:
      - hadoop_net

networks:
  hadoop_net: