name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [ '2.11', '2.12' ]
        spark: [ '2.4.5', '3.0.0' ]
        include:
          - scala: '2.11'
            spark: '3.0.0'
            skip: true
    name: Scala ${{ matrix.scala }} / Spark ${{ matrix.spark }}, skipped=${{ matrix.skip }}

    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/
          key: ${{ matrix.scala }}-${{ matrix.spark }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.scala }}-${{ matrix.spark }}-maven-
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #- name: Build
      #  if: '!matrix.skip'
      #  run: |
      #    export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
      #    export MAVEN_CLI_OPTS="-B --no-transfer-progress"
      #    mvn $MAVEN_CLI_OPTS -P CI,scala-${{ matrix.scala }} -Dspark.version=${{ matrix.spark }} clean site
      #    rm -rf ~/.m2/repository/io/github/phymbert
      - name: Start spark stack
        run: |
          docker-compose -f integration/docker-compose.yml up -d
          curl -v --retry 10 --retry-connrefused http://localhost:8080/